# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream/PynqZ1AES-AXI-stream.srcs/sources_1/bd/ZAES/ip/ZAES_axi_dma_0_2/ZAES_axi_dma_0_2.xci
# IP: The module: 'ZAES_axi_dma_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream/PynqZ1AES-AXI-stream.srcs/sources_1/bd/ZAES/ip/ZAES_axi_dma_0_2/ZAES_axi_dma_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZAES_axi_dma_0_2'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream/PynqZ1AES-AXI-stream.srcs/sources_1/bd/ZAES/ip/ZAES_axi_dma_0_2/ZAES_axi_dma_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZAES_axi_dma_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream/PynqZ1AES-AXI-stream.srcs/sources_1/bd/ZAES/ip/ZAES_axi_dma_0_2/ZAES_axi_dma_0_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZAES_axi_dma_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream/PynqZ1AES-AXI-stream.srcs/sources_1/bd/ZAES/ip/ZAES_axi_dma_0_2/ZAES_axi_dma_0_2.xci
# IP: The module: 'ZAES_axi_dma_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream/PynqZ1AES-AXI-stream.srcs/sources_1/bd/ZAES/ip/ZAES_axi_dma_0_2/ZAES_axi_dma_0_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZAES_axi_dma_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream/PynqZ1AES-AXI-stream.srcs/sources_1/bd/ZAES/ip/ZAES_axi_dma_0_2/ZAES_axi_dma_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZAES_axi_dma_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream/PynqZ1AES-AXI-stream.srcs/sources_1/bd/ZAES/ip/ZAES_axi_dma_0_2/ZAES_axi_dma_0_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZAES_axi_dma_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
