# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES/PynqZ1AES.srcs/sources_1/bd/ZAES/ip/ZAES_auto_pc_0/ZAES_auto_pc_0.xci
# IP: The module: 'ZAES_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES/PynqZ1AES.srcs/sources_1/bd/ZAES/ip/ZAES_auto_pc_0/ZAES_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZAES_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES/PynqZ1AES.srcs/sources_1/bd/ZAES/ip/ZAES_auto_pc_0/ZAES_auto_pc_0.xci
# IP: The module: 'ZAES_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES/PynqZ1AES.srcs/sources_1/bd/ZAES/ip/ZAES_auto_pc_0/ZAES_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZAES_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
