# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.cache/wt [current_project]
set_property parent.project_path D:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part www.digilentinc.com:pynq-z1:part0:1.0 [current_project]
set_property ip_repo_paths {
  d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/AES_Full_axis128/solution1/impl
  d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/axi4_stream_join_ip
  d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/axi4_stream_split_ip
} [current_project]
update_ip_catalog
set_property ip_output_repo d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib D:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/hdl/ZynqAES_wrapper.v
add_files D:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ZynqAES.bd
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_processing_system7_0_0/ZynqAES_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_1/bd_3e2c_psr_aclk_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_1/bd_3e2c_psr_aclk_0.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_2/bd_3e2c_arsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_3/bd_3e2c_rsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_4/bd_3e2c_awsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_5/bd_3e2c_wsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_6/bd_3e2c_bsw_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_10/bd_3e2c_s00a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_11/bd_3e2c_sarn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_12/bd_3e2c_srn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_16/bd_3e2c_s01a2s_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_17/bd_3e2c_sawn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_18/bd_3e2c_swn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_19/bd_3e2c_sbn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_20/bd_3e2c_m00s2a_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_21/bd_3e2c_m00arn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_22/bd_3e2c_m00rn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_23/bd_3e2c_m00awn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_24/bd_3e2c_m00wn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_smc_0/bd_0/ip/ip_25/bd_3e2c_m00bn_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_rst_ps7_0_100M_2/ZynqAES_rst_ps7_0_100M_2_board.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_rst_ps7_0_100M_2/ZynqAES_rst_ps7_0_100M_2.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_rst_ps7_0_100M_2/ZynqAES_rst_ps7_0_100M_2_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_xbar_1/ZynqAES_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_dma_0_1/ZynqAES_axi_dma_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_dma_0_1/ZynqAES_axi_dma_0_1.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_axi_dma_0_1/ZynqAES_axi_dma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_AES_Full_axis128_0_1/constraints/AES_Full_axis128_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_auto_pc_0/ZynqAES_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ZynqAES_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top ZynqAES_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef ZynqAES_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file ZynqAES_wrapper_utilization_synth.rpt -pb ZynqAES_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
