# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_xbar_1/ZynqAES_xbar_1.xci
# IP: The module: 'ZynqAES_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_xbar_1/ZynqAES_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqAES_xbar_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_xbar_1/ZynqAES_xbar_1.xci
# IP: The module: 'ZynqAES_xbar_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/OneDrive/UVA/crypto/AES_implementations/VivadoHLS/PynqZ1AES-AXI-stream128/PynqZ1AES-AXI-stream128.srcs/sources_1/bd/ZynqAES/ip/ZynqAES_xbar_1/ZynqAES_xbar_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ZynqAES_xbar_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
