# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/ZAES/ZAES.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZAES || ORIG_REF_NAME==ZAES} -quiet] -quiet

# IP: bd/ZAES/ip/ZAES_processing_system7_0_0/ZAES_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZAES_processing_system7_0_0 || ORIG_REF_NAME==ZAES_processing_system7_0_0} -quiet] -quiet

# IP: bd/ZAES/ip/ZAES_AES_Full_0_0/ZAES_AES_Full_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZAES_AES_Full_0_0 || ORIG_REF_NAME==ZAES_AES_Full_0_0} -quiet] -quiet

# IP: bd/ZAES/ip/ZAES_ps7_0_axi_periph_0/ZAES_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZAES_ps7_0_axi_periph_0 || ORIG_REF_NAME==ZAES_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ZAES/ip/ZAES_rst_ps7_0_100M_0/ZAES_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZAES_rst_ps7_0_100M_0 || ORIG_REF_NAME==ZAES_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ZAES/ip/ZAES_auto_pc_0/ZAES_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ZAES_auto_pc_0 || ORIG_REF_NAME==ZAES_auto_pc_0} -quiet] -quiet

# XDC: bd/ZAES/ZAES_ooc.xdc
