-- Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2018.3 (win64) Build 2405991 Thu Dec  6 23:38:27 MST 2018
-- Date        : Fri Apr  5 16:07:49 2019
-- Host        : HPLP-SM7ED running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ ZynqAES_axi4_stream_split_0_0_sim_netlist.vhdl
-- Design      : ZynqAES_axi4_stream_split_0_0
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xc7z020clg400-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  port (
    in_data_TDATA : in STD_LOGIC_VECTOR ( 127 downto 0 );
    in_data_TVALID : in STD_LOGIC;
    in_data_TREADY : out STD_LOGIC;
    out_data00_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data00_TVALID : out STD_LOGIC;
    out_data00_TREADY : in STD_LOGIC;
    out_data01_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data01_TVALID : out STD_LOGIC;
    out_data01_TREADY : in STD_LOGIC;
    out_data02_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data02_TVALID : out STD_LOGIC;
    out_data02_TREADY : in STD_LOGIC;
    out_data03_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data03_TVALID : out STD_LOGIC;
    out_data03_TREADY : in STD_LOGIC;
    out_data04_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data04_TVALID : out STD_LOGIC;
    out_data04_TREADY : in STD_LOGIC;
    out_data05_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data05_TVALID : out STD_LOGIC;
    out_data05_TREADY : in STD_LOGIC;
    out_data06_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data06_TVALID : out STD_LOGIC;
    out_data06_TREADY : in STD_LOGIC;
    out_data07_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data07_TVALID : out STD_LOGIC;
    out_data07_TREADY : in STD_LOGIC;
    out_data08_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data08_TVALID : out STD_LOGIC;
    out_data08_TREADY : in STD_LOGIC;
    out_data09_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data09_TVALID : out STD_LOGIC;
    out_data09_TREADY : in STD_LOGIC;
    out_data10_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data10_TVALID : out STD_LOGIC;
    out_data10_TREADY : in STD_LOGIC;
    out_data11_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data11_TVALID : out STD_LOGIC;
    out_data11_TREADY : in STD_LOGIC;
    out_data12_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data12_TVALID : out STD_LOGIC;
    out_data12_TREADY : in STD_LOGIC;
    out_data13_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data13_TVALID : out STD_LOGIC;
    out_data13_TREADY : in STD_LOGIC;
    out_data14_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data14_TVALID : out STD_LOGIC;
    out_data14_TREADY : in STD_LOGIC;
    out_data15_TDATA : out STD_LOGIC_VECTOR ( 7 downto 0 );
    out_data15_TVALID : out STD_LOGIC;
    out_data15_TREADY : in STD_LOGIC
  );
  attribute NotValidForBitStream : boolean;
  attribute NotValidForBitStream of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is true;
  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "ZynqAES_axi4_stream_split_0_0,axi4_stream_split,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "package_project";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "axi4_stream_split,Vivado 2018.3";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture STRUCTURE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  signal \^in_data_tdata\ : STD_LOGIC_VECTOR ( 127 downto 0 );
  signal \^in_data_tvalid\ : STD_LOGIC;
  signal \^out_data00_tready\ : STD_LOGIC;
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of in_data_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data TREADY";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of in_data_TREADY : signal is "XIL_INTERFACENAME in_data, TDATA_NUM_BYTES 16, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data TVALID";
  attribute X_INTERFACE_INFO of out_data00_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data00 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data00_TREADY : signal is "XIL_INTERFACENAME out_data00, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data00_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data00 TVALID";
  attribute X_INTERFACE_INFO of out_data01_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data01 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data01_TREADY : signal is "XIL_INTERFACENAME out_data01, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data01_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data01 TVALID";
  attribute X_INTERFACE_INFO of out_data02_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data02 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data02_TREADY : signal is "XIL_INTERFACENAME out_data02, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data02_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data02 TVALID";
  attribute X_INTERFACE_INFO of out_data03_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data03 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data03_TREADY : signal is "XIL_INTERFACENAME out_data03, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data03_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data03 TVALID";
  attribute X_INTERFACE_INFO of out_data04_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data04 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data04_TREADY : signal is "XIL_INTERFACENAME out_data04, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data04_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data04 TVALID";
  attribute X_INTERFACE_INFO of out_data05_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data05 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data05_TREADY : signal is "XIL_INTERFACENAME out_data05, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data05_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data05 TVALID";
  attribute X_INTERFACE_INFO of out_data06_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data06 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data06_TREADY : signal is "XIL_INTERFACENAME out_data06, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data06_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data06 TVALID";
  attribute X_INTERFACE_INFO of out_data07_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data07 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data07_TREADY : signal is "XIL_INTERFACENAME out_data07, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data07_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data07 TVALID";
  attribute X_INTERFACE_INFO of out_data08_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data08 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data08_TREADY : signal is "XIL_INTERFACENAME out_data08, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data08_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data08 TVALID";
  attribute X_INTERFACE_INFO of out_data09_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data09 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data09_TREADY : signal is "XIL_INTERFACENAME out_data09, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data09_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data09 TVALID";
  attribute X_INTERFACE_INFO of out_data10_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data10 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data10_TREADY : signal is "XIL_INTERFACENAME out_data10, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data10_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data10 TVALID";
  attribute X_INTERFACE_INFO of out_data11_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data11 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data11_TREADY : signal is "XIL_INTERFACENAME out_data11, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data11_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data11 TVALID";
  attribute X_INTERFACE_INFO of out_data12_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data12 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data12_TREADY : signal is "XIL_INTERFACENAME out_data12, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data12_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data12 TVALID";
  attribute X_INTERFACE_INFO of out_data13_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data13 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data13_TREADY : signal is "XIL_INTERFACENAME out_data13, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data13_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data13 TVALID";
  attribute X_INTERFACE_INFO of out_data14_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data14 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data14_TREADY : signal is "XIL_INTERFACENAME out_data14, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data14_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data14 TVALID";
  attribute X_INTERFACE_INFO of out_data15_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data15 TREADY";
  attribute X_INTERFACE_PARAMETER of out_data15_TREADY : signal is "XIL_INTERFACENAME out_data15, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data15_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data15 TVALID";
  attribute X_INTERFACE_INFO of in_data_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data TDATA";
  attribute X_INTERFACE_INFO of out_data00_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data00 TDATA";
  attribute X_INTERFACE_INFO of out_data01_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data01 TDATA";
  attribute X_INTERFACE_INFO of out_data02_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data02 TDATA";
  attribute X_INTERFACE_INFO of out_data03_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data03 TDATA";
  attribute X_INTERFACE_INFO of out_data04_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data04 TDATA";
  attribute X_INTERFACE_INFO of out_data05_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data05 TDATA";
  attribute X_INTERFACE_INFO of out_data06_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data06 TDATA";
  attribute X_INTERFACE_INFO of out_data07_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data07 TDATA";
  attribute X_INTERFACE_INFO of out_data08_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data08 TDATA";
  attribute X_INTERFACE_INFO of out_data09_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data09 TDATA";
  attribute X_INTERFACE_INFO of out_data10_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data10 TDATA";
  attribute X_INTERFACE_INFO of out_data11_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data11 TDATA";
  attribute X_INTERFACE_INFO of out_data12_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data12 TDATA";
  attribute X_INTERFACE_INFO of out_data13_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data13 TDATA";
  attribute X_INTERFACE_INFO of out_data14_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data14 TDATA";
  attribute X_INTERFACE_INFO of out_data15_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data15 TDATA";
begin
  \^in_data_tdata\(127 downto 0) <= in_data_TDATA(127 downto 0);
  \^in_data_tvalid\ <= in_data_TVALID;
  \^out_data00_tready\ <= out_data00_TREADY;
  in_data_TREADY <= \^out_data00_tready\;
  out_data00_TDATA(7 downto 0) <= \^in_data_tdata\(127 downto 120);
  out_data00_TVALID <= \^in_data_tvalid\;
  out_data01_TDATA(7 downto 0) <= \^in_data_tdata\(119 downto 112);
  out_data01_TVALID <= \^in_data_tvalid\;
  out_data02_TDATA(7 downto 0) <= \^in_data_tdata\(111 downto 104);
  out_data02_TVALID <= \^in_data_tvalid\;
  out_data03_TDATA(7 downto 0) <= \^in_data_tdata\(103 downto 96);
  out_data03_TVALID <= \^in_data_tvalid\;
  out_data04_TDATA(7 downto 0) <= \^in_data_tdata\(95 downto 88);
  out_data04_TVALID <= \^in_data_tvalid\;
  out_data05_TDATA(7 downto 0) <= \^in_data_tdata\(87 downto 80);
  out_data05_TVALID <= \^in_data_tvalid\;
  out_data06_TDATA(7 downto 0) <= \^in_data_tdata\(79 downto 72);
  out_data06_TVALID <= \^in_data_tvalid\;
  out_data07_TDATA(7 downto 0) <= \^in_data_tdata\(71 downto 64);
  out_data07_TVALID <= \^in_data_tvalid\;
  out_data08_TDATA(7 downto 0) <= \^in_data_tdata\(63 downto 56);
  out_data08_TVALID <= \^in_data_tvalid\;
  out_data09_TDATA(7 downto 0) <= \^in_data_tdata\(55 downto 48);
  out_data09_TVALID <= \^in_data_tvalid\;
  out_data10_TDATA(7 downto 0) <= \^in_data_tdata\(47 downto 40);
  out_data10_TVALID <= \^in_data_tvalid\;
  out_data11_TDATA(7 downto 0) <= \^in_data_tdata\(39 downto 32);
  out_data11_TVALID <= \^in_data_tvalid\;
  out_data12_TDATA(7 downto 0) <= \^in_data_tdata\(31 downto 24);
  out_data12_TVALID <= \^in_data_tvalid\;
  out_data13_TDATA(7 downto 0) <= \^in_data_tdata\(23 downto 16);
  out_data13_TVALID <= \^in_data_tvalid\;
  out_data14_TDATA(7 downto 0) <= \^in_data_tdata\(15 downto 8);
  out_data14_TVALID <= \^in_data_tvalid\;
  out_data15_TDATA(7 downto 0) <= \^in_data_tdata\(7 downto 0);
  out_data15_TVALID <= \^in_data_tvalid\;
end STRUCTURE;
