-- Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2018.3 (win64) Build 2405991 Thu Dec  6 23:38:27 MST 2018
-- Date        : Fri Apr  5 16:06:59 2019
-- Host        : HPLP-SM7ED running 64-bit major release  (build 9200)
-- Command     : write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ ZynqAES_axi4_stream_join_0_1_sim_netlist.vhdl
-- Design      : ZynqAES_axi4_stream_join_0_1
-- Purpose     : This VHDL netlist is a functional simulation representation of the design and should not be modified or
--               synthesized. This netlist cannot be used for SDF annotated simulation.
-- Device      : xc7z020clg400-1
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;
library UNISIM;
use UNISIM.VCOMPONENTS.ALL;
entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  port (
    in_data00_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data00_TVALID : in STD_LOGIC;
    in_data00_TREADY : out STD_LOGIC;
    in_data01_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data01_TVALID : in STD_LOGIC;
    in_data01_TREADY : out STD_LOGIC;
    in_data02_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data02_TVALID : in STD_LOGIC;
    in_data02_TREADY : out STD_LOGIC;
    in_data03_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data03_TVALID : in STD_LOGIC;
    in_data03_TREADY : out STD_LOGIC;
    in_data04_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data04_TVALID : in STD_LOGIC;
    in_data04_TREADY : out STD_LOGIC;
    in_data05_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data05_TVALID : in STD_LOGIC;
    in_data05_TREADY : out STD_LOGIC;
    in_data06_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data06_TVALID : in STD_LOGIC;
    in_data06_TREADY : out STD_LOGIC;
    in_data07_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data07_TVALID : in STD_LOGIC;
    in_data07_TREADY : out STD_LOGIC;
    in_data08_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data08_TVALID : in STD_LOGIC;
    in_data08_TREADY : out STD_LOGIC;
    in_data09_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data09_TVALID : in STD_LOGIC;
    in_data09_TREADY : out STD_LOGIC;
    in_data10_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data10_TVALID : in STD_LOGIC;
    in_data10_TREADY : out STD_LOGIC;
    in_data11_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data11_TVALID : in STD_LOGIC;
    in_data11_TREADY : out STD_LOGIC;
    in_data12_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data12_TVALID : in STD_LOGIC;
    in_data12_TREADY : out STD_LOGIC;
    in_data13_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data13_TVALID : in STD_LOGIC;
    in_data13_TREADY : out STD_LOGIC;
    in_data14_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data14_TVALID : in STD_LOGIC;
    in_data14_TREADY : out STD_LOGIC;
    in_data15_TDATA : in STD_LOGIC_VECTOR ( 7 downto 0 );
    in_data15_TVALID : in STD_LOGIC;
    in_data15_TREADY : out STD_LOGIC;
    out_data_TDATA : out STD_LOGIC_VECTOR ( 127 downto 0 );
    out_data_TVALID : out STD_LOGIC;
    out_data_TREADY : in STD_LOGIC
  );
  attribute NotValidForBitStream : boolean;
  attribute NotValidForBitStream of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is true;
  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "ZynqAES_axi4_stream_join_0_1,axi4_stream_join,{}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "package_project";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "axi4_stream_join,Vivado 2018.3";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture STRUCTURE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  signal \^in_data00_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^in_data00_tvalid\ : STD_LOGIC;
  signal \^in_data01_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^in_data02_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^in_data03_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^in_data04_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^in_data05_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^in_data06_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^in_data07_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^in_data08_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^in_data09_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^in_data10_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^in_data11_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^in_data12_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^in_data13_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^in_data14_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^in_data15_tdata\ : STD_LOGIC_VECTOR ( 7 downto 0 );
  signal \^out_data_tready\ : STD_LOGIC;
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of in_data00_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data00 TREADY";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of in_data00_TREADY : signal is "XIL_INTERFACENAME in_data00, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data00_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data00 TVALID";
  attribute X_INTERFACE_INFO of in_data01_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data01 TREADY";
  attribute X_INTERFACE_PARAMETER of in_data01_TREADY : signal is "XIL_INTERFACENAME in_data01, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data01_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data01 TVALID";
  attribute X_INTERFACE_INFO of in_data02_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data02 TREADY";
  attribute X_INTERFACE_PARAMETER of in_data02_TREADY : signal is "XIL_INTERFACENAME in_data02, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data02_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data02 TVALID";
  attribute X_INTERFACE_INFO of in_data03_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data03 TREADY";
  attribute X_INTERFACE_PARAMETER of in_data03_TREADY : signal is "XIL_INTERFACENAME in_data03, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data03_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data03 TVALID";
  attribute X_INTERFACE_INFO of in_data04_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data04 TREADY";
  attribute X_INTERFACE_PARAMETER of in_data04_TREADY : signal is "XIL_INTERFACENAME in_data04, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data04_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data04 TVALID";
  attribute X_INTERFACE_INFO of in_data05_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data05 TREADY";
  attribute X_INTERFACE_PARAMETER of in_data05_TREADY : signal is "XIL_INTERFACENAME in_data05, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data05_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data05 TVALID";
  attribute X_INTERFACE_INFO of in_data06_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data06 TREADY";
  attribute X_INTERFACE_PARAMETER of in_data06_TREADY : signal is "XIL_INTERFACENAME in_data06, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data06_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data06 TVALID";
  attribute X_INTERFACE_INFO of in_data07_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data07 TREADY";
  attribute X_INTERFACE_PARAMETER of in_data07_TREADY : signal is "XIL_INTERFACENAME in_data07, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data07_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data07 TVALID";
  attribute X_INTERFACE_INFO of in_data08_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data08 TREADY";
  attribute X_INTERFACE_PARAMETER of in_data08_TREADY : signal is "XIL_INTERFACENAME in_data08, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data08_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data08 TVALID";
  attribute X_INTERFACE_INFO of in_data09_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data09 TREADY";
  attribute X_INTERFACE_PARAMETER of in_data09_TREADY : signal is "XIL_INTERFACENAME in_data09, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data09_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data09 TVALID";
  attribute X_INTERFACE_INFO of in_data10_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data10 TREADY";
  attribute X_INTERFACE_PARAMETER of in_data10_TREADY : signal is "XIL_INTERFACENAME in_data10, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data10_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data10 TVALID";
  attribute X_INTERFACE_INFO of in_data11_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data11 TREADY";
  attribute X_INTERFACE_PARAMETER of in_data11_TREADY : signal is "XIL_INTERFACENAME in_data11, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data11_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data11 TVALID";
  attribute X_INTERFACE_INFO of in_data12_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data12 TREADY";
  attribute X_INTERFACE_PARAMETER of in_data12_TREADY : signal is "XIL_INTERFACENAME in_data12, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data12_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data12 TVALID";
  attribute X_INTERFACE_INFO of in_data13_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data13 TREADY";
  attribute X_INTERFACE_PARAMETER of in_data13_TREADY : signal is "XIL_INTERFACENAME in_data13, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data13_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data13 TVALID";
  attribute X_INTERFACE_INFO of in_data14_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data14 TREADY";
  attribute X_INTERFACE_PARAMETER of in_data14_TREADY : signal is "XIL_INTERFACENAME in_data14, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data14_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data14 TVALID";
  attribute X_INTERFACE_INFO of in_data15_TREADY : signal is "xilinx.com:interface:axis:1.0 in_data15 TREADY";
  attribute X_INTERFACE_PARAMETER of in_data15_TREADY : signal is "XIL_INTERFACENAME in_data15, TDATA_NUM_BYTES 1, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA xilinx.com:interface:datatypes:1.0 {CLK {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 1} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0}}} TDATA {datatype {name {attribs {resolve_type immediate dependency {} format string minimum {} maximum {}} value {}} bitwidth {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 8} bitoffset {attribs {resolve_type immediate dependency {} format long minimum {} maximum {}} value 0} integer {signed {attribs {resolve_type immediate dependency {} format bool minimum {} maximum {}} value false}}}} TDATA_WIDTH 8}, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of in_data15_TVALID : signal is "xilinx.com:interface:axis:1.0 in_data15 TVALID";
  attribute X_INTERFACE_INFO of out_data_TREADY : signal is "xilinx.com:interface:axis:1.0 out_data TREADY";
  attribute X_INTERFACE_PARAMETER of out_data_TREADY : signal is "XIL_INTERFACENAME out_data, TDATA_NUM_BYTES 16, TDEST_WIDTH 0, TID_WIDTH 0, TUSER_WIDTH 0, HAS_TREADY 1, HAS_TSTRB 0, HAS_TKEEP 0, HAS_TLAST 0, FREQ_HZ 100000000, PHASE 0.000, LAYERED_METADATA undef, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of out_data_TVALID : signal is "xilinx.com:interface:axis:1.0 out_data TVALID";
  attribute X_INTERFACE_INFO of in_data00_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data00 TDATA";
  attribute X_INTERFACE_INFO of in_data01_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data01 TDATA";
  attribute X_INTERFACE_INFO of in_data02_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data02 TDATA";
  attribute X_INTERFACE_INFO of in_data03_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data03 TDATA";
  attribute X_INTERFACE_INFO of in_data04_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data04 TDATA";
  attribute X_INTERFACE_INFO of in_data05_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data05 TDATA";
  attribute X_INTERFACE_INFO of in_data06_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data06 TDATA";
  attribute X_INTERFACE_INFO of in_data07_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data07 TDATA";
  attribute X_INTERFACE_INFO of in_data08_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data08 TDATA";
  attribute X_INTERFACE_INFO of in_data09_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data09 TDATA";
  attribute X_INTERFACE_INFO of in_data10_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data10 TDATA";
  attribute X_INTERFACE_INFO of in_data11_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data11 TDATA";
  attribute X_INTERFACE_INFO of in_data12_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data12 TDATA";
  attribute X_INTERFACE_INFO of in_data13_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data13 TDATA";
  attribute X_INTERFACE_INFO of in_data14_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data14 TDATA";
  attribute X_INTERFACE_INFO of in_data15_TDATA : signal is "xilinx.com:interface:axis:1.0 in_data15 TDATA";
  attribute X_INTERFACE_INFO of out_data_TDATA : signal is "xilinx.com:interface:axis:1.0 out_data TDATA";
begin
  \^in_data00_tdata\(7 downto 0) <= in_data00_TDATA(7 downto 0);
  \^in_data00_tvalid\ <= in_data00_TVALID;
  \^in_data01_tdata\(7 downto 0) <= in_data01_TDATA(7 downto 0);
  \^in_data02_tdata\(7 downto 0) <= in_data02_TDATA(7 downto 0);
  \^in_data03_tdata\(7 downto 0) <= in_data03_TDATA(7 downto 0);
  \^in_data04_tdata\(7 downto 0) <= in_data04_TDATA(7 downto 0);
  \^in_data05_tdata\(7 downto 0) <= in_data05_TDATA(7 downto 0);
  \^in_data06_tdata\(7 downto 0) <= in_data06_TDATA(7 downto 0);
  \^in_data07_tdata\(7 downto 0) <= in_data07_TDATA(7 downto 0);
  \^in_data08_tdata\(7 downto 0) <= in_data08_TDATA(7 downto 0);
  \^in_data09_tdata\(7 downto 0) <= in_data09_TDATA(7 downto 0);
  \^in_data10_tdata\(7 downto 0) <= in_data10_TDATA(7 downto 0);
  \^in_data11_tdata\(7 downto 0) <= in_data11_TDATA(7 downto 0);
  \^in_data12_tdata\(7 downto 0) <= in_data12_TDATA(7 downto 0);
  \^in_data13_tdata\(7 downto 0) <= in_data13_TDATA(7 downto 0);
  \^in_data14_tdata\(7 downto 0) <= in_data14_TDATA(7 downto 0);
  \^in_data15_tdata\(7 downto 0) <= in_data15_TDATA(7 downto 0);
  \^out_data_tready\ <= out_data_TREADY;
  in_data00_TREADY <= \^out_data_tready\;
  in_data01_TREADY <= \^out_data_tready\;
  in_data02_TREADY <= \^out_data_tready\;
  in_data03_TREADY <= \^out_data_tready\;
  in_data04_TREADY <= \^out_data_tready\;
  in_data05_TREADY <= \^out_data_tready\;
  in_data06_TREADY <= \^out_data_tready\;
  in_data07_TREADY <= \^out_data_tready\;
  in_data08_TREADY <= \^out_data_tready\;
  in_data09_TREADY <= \^out_data_tready\;
  in_data10_TREADY <= \^out_data_tready\;
  in_data11_TREADY <= \^out_data_tready\;
  in_data12_TREADY <= \^out_data_tready\;
  in_data13_TREADY <= \^out_data_tready\;
  in_data14_TREADY <= \^out_data_tready\;
  in_data15_TREADY <= \^out_data_tready\;
  out_data_TDATA(127 downto 120) <= \^in_data00_tdata\(7 downto 0);
  out_data_TDATA(119 downto 112) <= \^in_data01_tdata\(7 downto 0);
  out_data_TDATA(111 downto 104) <= \^in_data02_tdata\(7 downto 0);
  out_data_TDATA(103 downto 96) <= \^in_data03_tdata\(7 downto 0);
  out_data_TDATA(95 downto 88) <= \^in_data04_tdata\(7 downto 0);
  out_data_TDATA(87 downto 80) <= \^in_data05_tdata\(7 downto 0);
  out_data_TDATA(79 downto 72) <= \^in_data06_tdata\(7 downto 0);
  out_data_TDATA(71 downto 64) <= \^in_data07_tdata\(7 downto 0);
  out_data_TDATA(63 downto 56) <= \^in_data08_tdata\(7 downto 0);
  out_data_TDATA(55 downto 48) <= \^in_data09_tdata\(7 downto 0);
  out_data_TDATA(47 downto 40) <= \^in_data10_tdata\(7 downto 0);
  out_data_TDATA(39 downto 32) <= \^in_data11_tdata\(7 downto 0);
  out_data_TDATA(31 downto 24) <= \^in_data12_tdata\(7 downto 0);
  out_data_TDATA(23 downto 16) <= \^in_data13_tdata\(7 downto 0);
  out_data_TDATA(15 downto 8) <= \^in_data14_tdata\(7 downto 0);
  out_data_TDATA(7 downto 0) <= \^in_data15_tdata\(7 downto 0);
  out_data_TVALID <= \^in_data00_tvalid\;
end STRUCTURE;
